MODEL_OWNERS = {
    "SystemRole": "accounts",
    "ProjectRole": "projects",
    "JobState": "pipeline",
    "AnnotationKind": "documents",
    "AnnotationScope": "documents",
    "FileRevisionProcessingState": "documents",
    "User": "accounts",
    "LoginSession": "accounts",
    "LoginThrottle": "accounts",
    "Invitation": "accounts",
    "Item": "library",
    "Author": "library",
    "ItemAuthor": "library",
    "ItemIdentifier": "library",
    "ItemRead": "library",
    "Project": "projects",
    "ProjectMember": "projects",
    "ProjectItem": "projects",
    "Tag": "library",
    "ItemTag": "library",
    "DiscussionMessage": "library",
    "FileRevision": "documents",
    "Attachment": "documents",
    "PdfAnnotation": "documents",
    "PdfAnnotationSegment": "documents",
    "Job": "pipeline",
    "ImportBatch": "discovery",
    "CitationStyle": "discovery",
    "AuditEvent": "audit",
    "SystemSetting": "operations",
}

CROSS_CAPABILITY_RELATIONSHIPS = (
    ("Item", "User"),
    ("Item", "FileRevision"),
    ("FileRevision", "Item"),
    ("PdfAnnotation", "FileRevision"),
    ("PdfAnnotation", "User"),
    ("PdfAnnotation", "Project"),
    ("ProjectItem", "Project"),
    ("ProjectItem", "Item"),
    ("Job", "User"),
    ("ImportBatch", "User"),
    ("CitationStyle", "User"),
    ("AuditEvent", "User"),
    ("SystemSetting", "User"),
)
