"""Shared contracts and pure projections for programmatic inbound adapters."""

from quirebase.programmatic.projections import (
    discussion_message_views,
    document_list_view,
    item_detail_view,
    item_search_view,
    project_detail_view,
)
from quirebase.programmatic.views import (
    AnnotationReplyView,
    AnnotationView,
    AuthorSuggestionView,
    CitationStyleItemView,
    CitationStylesResponseView,
    CitationView,
    ContributorView,
    DiscoveryProviderView,
    DiscussionMessageView,
    DocumentListView,
    FileView,
    ItemDetailView,
    ItemSearchView,
    JoinableProjectView,
    LibrarySearchView,
    OkView,
    ProjectDetailView,
    ProjectMemberView,
    ProjectSummaryView,
    TagView,
    WorkflowStatusView,
    WriteResult,
)

__all__ = [
    "AnnotationReplyView",
    "AnnotationView",
    "AuthorSuggestionView",
    "CitationStyleItemView",
    "CitationStylesResponseView",
    "CitationView",
    "ContributorView",
    "DiscoveryProviderView",
    "DiscussionMessageView",
    "DocumentListView",
    "FileView",
    "ItemDetailView",
    "ItemSearchView",
    "JoinableProjectView",
    "LibrarySearchView",
    "OkView",
    "ProjectDetailView",
    "ProjectMemberView",
    "ProjectSummaryView",
    "TagView",
    "WorkflowStatusView",
    "WriteResult",
    "discussion_message_views",
    "document_list_view",
    "item_detail_view",
    "item_search_view",
    "project_detail_view",
]
