"""initial workspace schema

Revision ID: 8a60bab5df5d
Revises:
Create Date: 2026-10-09 16:31:16.893539

"""

import warnings
from typing import TYPE_CHECKING

import sqlalchemy as sa
from alembic import op
from advanced_alchemy.types import Bool, EncryptedString, EncryptedText, GUID, JsonB, ORA_JSONB, DateTimeUTC, StoredObject, PasswordHash, FernetBackend, TOTPSecret, OneTimeCode
from advanced_alchemy.types.encrypted_string import PGCryptoBackend
from advanced_alchemy.types.password_hash.argon2 import Argon2Hasher
from advanced_alchemy.types.password_hash.passlib import PasslibHasher
from advanced_alchemy.types.password_hash.pwdlib import PwdlibHasher
from sqlalchemy import Text  # noqa: F401
from sqlalchemy.dialects import postgresql

if TYPE_CHECKING:
    from collections.abc import Sequence

__all__ = ("downgrade", "upgrade", "schema_upgrades", "schema_downgrades", "data_upgrades", "data_downgrades")

sa.GUID = GUID
sa.Bool = Bool
sa.DateTimeUTC = DateTimeUTC
sa.JsonB = JsonB
sa.ORA_JSONB = ORA_JSONB
sa.EncryptedString = EncryptedString
sa.EncryptedText = EncryptedText
sa.StoredObject = StoredObject
sa.PasswordHash = PasswordHash
sa.Argon2Hasher = Argon2Hasher
sa.PasslibHasher = PasslibHasher
sa.PwdlibHasher = PwdlibHasher
sa.FernetBackend = FernetBackend
sa.PGCryptoBackend = PGCryptoBackend
sa.TOTPSecret = TOTPSecret
sa.OneTimeCode = OneTimeCode

# revision identifiers, used by Alembic.
revision = '8a60bab5df5d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            schema_upgrades()
            data_upgrades()

def downgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            data_downgrades()
            schema_downgrades()

def schema_upgrades() -> None:
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authors',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('first_name', sa.String(length=120), nullable=True),
    sa.Column('last_name', sa.String(length=120), nullable=False),
    sa.Column('identity_key', sa.String(length=512), nullable=False),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_authors')),
    sa.UniqueConstraint('identity_key', name='uq_authors_identity')
    )
    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_authors_last_name'), ['last_name'], unique=False)

    op.create_table('login_throttles',
    sa.Column('identity_hash', sa.String(length=64), nullable=False),
    sa.Column('failures', sa.Integer(), nullable=False),
    sa.Column('window_started_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('identity_hash', name=op.f('pk_login_throttles'))
    )
    op.create_table('object_integrity_scans',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('missing_count', sa.Integer(), nullable=False),
    sa.Column('mismatch_count', sa.Integer(), nullable=False),
    sa.Column('errors', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'cockroachdb').with_variant(sa.ORA_JSONB(), 'oracle').with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('checked_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_object_integrity_scans'))
    )
    with op.batch_alter_table('object_integrity_scans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_object_integrity_scans_checked_at'), ['checked_at'], unique=False)

    op.create_table('pdf_annotation_objects',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('object_type', sa.Enum('annotation', 'reply', name='annotation_object_type', native_enum=False), nullable=False),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.CheckConstraint("object_type IN ('annotation', 'reply')", name=op.f('ck_pdf_annotation_objects_type')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pdf_annotation_objects'))
    )
    op.create_table('users',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('api_tokens',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.GUID(length=16), nullable=False),
    sa.Column('expires_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTimeUTC(timezone=True), nullable=True),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_api_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_api_tokens'))
    )
    with op.batch_alter_table('api_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_tokens_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_tokens_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_api_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('audit_events',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('actor_id', sa.GUID(length=16), nullable=True),
    sa.Column('workspace_id', sa.GUID(length=16), nullable=True),
    sa.Column('project_id', sa.GUID(length=16), nullable=True),
    sa.Column('action', sa.String(length=120), nullable=False),
    sa.Column('target_type', sa.String(length=80), nullable=False),
    sa.Column('target_id', sa.String(length=36), nullable=True),
    sa.Column('detail', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'cockroachdb').with_variant(sa.ORA_JSONB(), 'oracle').with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('target_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'cockroachdb').with_variant(sa.ORA_JSONB(), 'oracle').with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('authorization_role', sa.String(length=32), nullable=True),
    sa.Column('authorization_resource_action', sa.String(length=80), nullable=True),
    sa.Column('result', sa.String(length=32), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_audit_events_actor_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_events'))
    )
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_events_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('invitations',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('created_by', sa.GUID(length=16), nullable=False),
    sa.Column('expires_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('accepted_at', sa.DateTimeUTC(timezone=True), nullable=True),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_invitations_created_by_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invitations')),
    sa.UniqueConstraint('username', name=op.f('uq_invitations_username'))
    )
    with op.batch_alter_table('invitations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invitations_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_invitations_token_hash'), ['token_hash'], unique=True)

    op.create_table('login_sessions',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.GUID(length=16), nullable=False),
    sa.Column('expires_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_login_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_login_sessions'))
    )
    with op.batch_alter_table('login_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_login_sessions_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_login_sessions_token_hash'), ['token_hash'], unique=True)

    op.create_table('system_settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_by', sa.GUID(length=16), nullable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_system_settings_updated_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_system_settings'))
    )
    op.create_table('workspaces',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('name', sa.String(length=240), nullable=False),
    sa.Column('created_by', sa.GUID(length=16), nullable=False),
    sa.Column('state', sa.Enum('active', 'archived', 'deleted', name='workspace_state', native_enum=False), nullable=False),
    sa.Column('governance_frozen_at', sa.DateTimeUTC(timezone=True), nullable=True),
    sa.Column('governance_frozen_by', sa.GUID(length=16), nullable=True),
    sa.Column('archived_at', sa.DateTimeUTC(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTimeUTC(timezone=True), nullable=True),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.CheckConstraint("state IN ('active', 'archived', 'deleted')", name=op.f('ck_workspaces_state')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_workspaces_created_by_users')),
    sa.ForeignKeyConstraint(['governance_frozen_by'], ['users.id'], name=op.f('fk_workspaces_governance_frozen_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workspaces'))
    )
    op.create_table('citation_styles',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('workspace_id', sa.GUID(length=16), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('csl_xml', sa.Text(), nullable=False),
    sa.Column('created_by', sa.GUID(length=16), nullable=False),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_citation_styles_created_by_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_citation_styles_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_citation_styles')),
    sa.UniqueConstraint('workspace_id', 'name', name='uq_citation_styles_workspace_name')
    )
    with op.batch_alter_table('citation_styles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_citation_styles_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_citation_styles_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('export_artifacts',
    sa.Column('workflow_id', sa.String(length=255), nullable=False),
    sa.Column('workspace_id', sa.GUID(length=16), nullable=False),
    sa.Column('file', sa.StoredObject(backend='documents'), nullable=False),
    sa.Column('expires_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_export_artifacts_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('workflow_id', name=op.f('pk_export_artifacts'))
    )
    with op.batch_alter_table('export_artifacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_export_artifacts_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_export_artifacts_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('import_batches',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('workspace_id', sa.GUID(length=16), nullable=False),
    sa.Column('actor_id', sa.GUID(length=16), nullable=False),
    sa.Column('file_format', sa.String(length=16), nullable=False),
    sa.Column('records', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'cockroachdb').with_variant(sa.ORA_JSONB(), 'oracle').with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('staged_files', sa.StoredObject(backend='documents', multiple=True), nullable=False),
    sa.Column('errors', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'cockroachdb').with_variant(sa.ORA_JSONB(), 'oracle').with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('workflow_id', sa.String(length=255), nullable=True),
    sa.Column('committed_item_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'cockroachdb').with_variant(sa.ORA_JSONB(), 'oracle').with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'ready', 'failed', 'committed')", name=op.f('ck_import_batches_status')),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_import_batches_actor_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_import_batches_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_import_batches'))
    )
    with op.batch_alter_table('import_batches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_import_batches_actor_id'), ['actor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_import_batches_workflow_id'), ['workflow_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_import_batches_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('items',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('workspace_id', sa.GUID(length=16), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('publication_date', sa.String(length=32), nullable=True),
    sa.Column('publication_title', sa.Text(), nullable=True),
    sa.Column('volume', sa.String(length=100), nullable=True),
    sa.Column('issue', sa.String(length=100), nullable=True),
    sa.Column('pages', sa.String(length=100), nullable=True),
    sa.Column('affiliation', sa.Text(), nullable=True),
    sa.Column('publisher', sa.Text(), nullable=True),
    sa.Column('place_published', sa.String(length=255), nullable=True),
    sa.Column('journal_abbreviation', sa.Text(), nullable=True),
    sa.Column('doi', sa.String(length=500), nullable=True),
    sa.Column('identifiers', sa.Text(), nullable=True),
    sa.Column('reference_type', sa.String(length=40), nullable=True),
    sa.Column('authors', sa.Text(), nullable=True),
    sa.Column('editors', sa.Text(), nullable=True),
    sa.Column('bibtex_id', sa.String(length=255), nullable=True),
    sa.Column('bibtex_type', sa.String(length=40), nullable=True),
    sa.Column('urls', sa.Text(), nullable=True),
    sa.Column('keywords', sa.Text(), nullable=True),
    sa.Column('custom_fields', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'cockroachdb').with_variant(sa.ORA_JSONB(), 'oracle').with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('created_by', sa.GUID(length=16), nullable=False),
    sa.Column('updated_by', sa.GUID(length=16), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_items_created_by_users')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_items_updated_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_items_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_items')),
    sa.UniqueConstraint('workspace_id', 'id', name='uq_items_workspace_id')
    )
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_items_bibtex_id'), ['bibtex_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_items_doi'), ['doi'], unique=False)
        batch_op.create_index(batch_op.f('ix_items_title'), ['title'], unique=False)
        batch_op.create_index(batch_op.f('ix_items_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('projects',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('workspace_id', sa.GUID(length=16), nullable=False),
    sa.Column('name', sa.String(length=240), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_by', sa.GUID(length=16), nullable=False),
    sa.Column('state', sa.Enum('active', 'archived', 'deleted', name='project_state', native_enum=False), nullable=False),
    sa.Column('participation', sa.Enum('workspace', 'open', 'managed', name='project_participation', native_enum=False), nullable=False),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.CheckConstraint("participation IN ('workspace', 'open', 'managed')", name=op.f('ck_projects_participation')),
    sa.CheckConstraint("state IN ('active', 'archived', 'deleted')", name=op.f('ck_projects_state')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_projects_created_by_users')),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_projects_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects')),
    sa.UniqueConstraint('workspace_id', 'id', name='uq_projects_workspace_id')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('tags',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('workspace_id', sa.GUID(length=16), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('normalized_name', sa.String(length=360), nullable=False),
    sa.Column('created_by', sa.GUID(length=16), nullable=False),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_tags_created_by_users')),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_tags_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tags')),
    sa.UniqueConstraint('workspace_id', 'id', name='uq_tags_workspace_id'),
    sa.UniqueConstraint('workspace_id', 'normalized_name', name='uq_tags_workspace_normalized')
    )
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tags_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_tags_normalized_name'), ['normalized_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_tags_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('workspace_invitations',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('workspace_id', sa.GUID(length=16), nullable=False),
    sa.Column('user_id', sa.GUID(length=16), nullable=False),
    sa.Column('role', sa.Enum('admin', 'editor', 'reviewer', 'viewer', name='workspace_invitation_role', native_enum=False), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('invited_by', sa.GUID(length=16), nullable=False),
    sa.Column('expires_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('accepted_at', sa.DateTimeUTC(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTimeUTC(timezone=True), nullable=True),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.CheckConstraint("role IN ('admin', 'editor', 'reviewer', 'viewer')", name=op.f('ck_workspace_invitations_role')),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], name=op.f('fk_workspace_invitations_invited_by_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_workspace_invitations_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_workspace_invitations_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workspace_invitations'))
    )
    with op.batch_alter_table('workspace_invitations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workspace_invitations_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_workspace_invitations_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_workspace_invitations_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workspace_invitations_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('workspace_members',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('workspace_id', sa.GUID(length=16), nullable=False),
    sa.Column('user_id', sa.GUID(length=16), nullable=False),
    sa.Column('role', sa.Enum('owner', 'admin', 'editor', 'reviewer', 'viewer', name='workspace_role', native_enum=False), nullable=False),
    sa.Column('state', sa.Enum('active', 'suspended', name='workspace_member_state', native_enum=False), nullable=False),
    sa.Column('invited_by', sa.GUID(length=16), nullable=True),
    sa.Column('suspended_at', sa.DateTimeUTC(timezone=True), nullable=True),
    sa.Column('terminated_at', sa.DateTimeUTC(timezone=True), nullable=True),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.CheckConstraint("role <> 'owner' OR (state = 'active' AND terminated_at IS NULL)", name=op.f('ck_workspace_members_owner_active')),
    sa.CheckConstraint("role IN ('owner', 'admin', 'editor', 'reviewer', 'viewer')", name=op.f('ck_workspace_members_role')),
    sa.CheckConstraint("state IN ('active', 'suspended')", name=op.f('ck_workspace_members_state')),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], name=op.f('fk_workspace_members_invited_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_workspace_members_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_workspace_members_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workspace_members')),
    sa.UniqueConstraint('workspace_id', 'id', 'user_id', name='uq_workspace_members_identity')
    )
    with op.batch_alter_table('workspace_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workspace_members_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workspace_members_workspace_id'), ['workspace_id'], unique=False)
        batch_op.create_index('uq_workspace_members_current', ['workspace_id', 'user_id'], unique=True, sqlite_where=sa.text('terminated_at IS NULL'), postgresql_where=sa.text('terminated_at IS NULL'))
        batch_op.create_index('uq_workspace_members_current_owner', ['workspace_id'], unique=True, sqlite_where=sa.text("terminated_at IS NULL AND role = 'owner'"), postgresql_where=sa.text("terminated_at IS NULL AND role = 'owner'"))

    op.create_table('attachments',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('workspace_id', sa.GUID(length=16), nullable=False),
    sa.Column('item_id', sa.GUID(length=16), nullable=False),
    sa.Column('file', sa.StoredObject(backend='documents'), nullable=False),
    sa.Column('role', sa.Enum('graphical_abstract', name='attachment_role', native_enum=False), nullable=True),
    sa.Column('created_by', sa.GUID(length=16), nullable=False),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.CheckConstraint("role IS NULL OR role = 'graphical_abstract'", name=op.f('ck_attachments_role')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_attachments_created_by_users')),
    sa.ForeignKeyConstraint(['workspace_id', 'item_id'], ['items.workspace_id', 'items.id'], name='fk_attachments_item_workspace', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attachments')),
    sa.UniqueConstraint('item_id', 'role', name='uq_attachments_item_role')
    )
    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attachments_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attachments_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('discussion_messages',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('workspace_id', sa.GUID(length=16), nullable=False),
    sa.Column('item_id', sa.GUID(length=16), nullable=True),
    sa.Column('project_id', sa.GUID(length=16), nullable=True),
    sa.Column('author_id', sa.GUID(length=16), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.CheckConstraint('(item_id IS NOT NULL AND project_id IS NULL) OR (item_id IS NULL AND project_id IS NOT NULL)', name=op.f('ck_discussion_messages_context')),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_discussion_messages_author_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id', 'item_id'], ['items.workspace_id', 'items.id'], name='fk_discussion_messages_item_workspace', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id', 'project_id'], ['projects.workspace_id', 'projects.id'], name='fk_discussion_messages_project_workspace', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_discussion_messages'))
    )
    with op.batch_alter_table('discussion_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_discussion_messages_author_id'), ['author_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_discussion_messages_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_discussion_messages_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_discussion_messages_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('file_revisions',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('workspace_id', sa.GUID(length=16), nullable=False),
    sa.Column('item_id', sa.GUID(length=16), nullable=False),
    sa.Column('file', sa.StoredObject(backend='documents'), nullable=False),
    sa.Column('thumbnail', sa.StoredObject(backend='documents'), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('page_geometry', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'cockroachdb').with_variant(sa.ORA_JSONB(), 'oracle').with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('full_text', sa.Text(), nullable=True),
    sa.Column('processing_state', sa.Enum('pending', 'ready', name='file_revision_processing_state', native_enum=False), nullable=False),
    sa.Column('created_by', sa.GUID(length=16), nullable=False),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.CheckConstraint("processing_state IN ('pending', 'ready')", name=op.f('ck_file_revisions_processing_state')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_file_revisions_created_by_users')),
    sa.ForeignKeyConstraint(['workspace_id', 'item_id'], ['items.workspace_id', 'items.id'], name='fk_file_revisions_item_workspace', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_file_revisions')),
    sa.UniqueConstraint('workspace_id', 'id', 'item_id', name='uq_file_revisions_workspace_id_item'),
    sa.UniqueConstraint('workspace_id', 'id', name='uq_file_revisions_workspace_id')
    )
    with op.batch_alter_table('file_revisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_file_revisions_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_file_revisions_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('item_authors',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('item_id', sa.GUID(length=16), nullable=False),
    sa.Column('author_id', sa.GUID(length=16), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_corresponding', sa.Boolean(), nullable=False),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['authors.id'], name=op.f('fk_item_authors_author_id_authors'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], name=op.f('fk_item_authors_item_id_items'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_item_authors')),
    sa.UniqueConstraint('item_id', 'author_id', 'role', name='uq_item_author_role')
    )
    with op.batch_alter_table('item_authors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_item_authors_author_id'), ['author_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_item_authors_item_id'), ['item_id'], unique=False)

    op.create_table('item_identifiers',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('item_id', sa.GUID(length=16), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('value', sa.String(length=500), nullable=False),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], name=op.f('fk_item_identifiers_item_id_items'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_item_identifiers')),
    sa.UniqueConstraint('item_id', 'provider', 'value', name='uq_item_provider_value')
    )
    with op.batch_alter_table('item_identifiers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_item_identifiers_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_item_identifiers_provider'), ['provider'], unique=False)
        batch_op.create_index(batch_op.f('ix_item_identifiers_value'), ['value'], unique=False)

    op.create_table('item_reads',
    sa.Column('user_id', sa.GUID(length=16), nullable=False),
    sa.Column('item_id', sa.GUID(length=16), nullable=False),
    sa.Column('workspace_id', sa.GUID(length=16), nullable=False),
    sa.Column('last_read_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_item_reads_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id', 'item_id'], ['items.workspace_id', 'items.id'], name='fk_item_reads_item_workspace', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'item_id', name=op.f('pk_item_reads'))
    )
    with op.batch_alter_table('item_reads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_item_reads_last_read_at'), ['last_read_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_item_reads_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('item_tag_recommendations',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('workspace_id', sa.GUID(length=16), nullable=False),
    sa.Column('item_id', sa.GUID(length=16), nullable=False),
    sa.Column('generation_token', sa.Integer(), nullable=False),
    sa.Column('workflow_id', sa.String(length=255), nullable=True),
    sa.Column('single_words', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'cockroachdb').with_variant(sa.ORA_JSONB(), 'oracle').with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('phrases', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'cockroachdb').with_variant(sa.ORA_JSONB(), 'oracle').with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('generated_at', sa.DateTimeUTC(timezone=True), nullable=True),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.CheckConstraint('generation_token >= 1', name=op.f('ck_item_tag_recommendations_token')),
    sa.ForeignKeyConstraint(['workspace_id', 'item_id'], ['items.workspace_id', 'items.id'], name='fk_item_tag_recommendations_item_workspace', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_item_tag_recommendations'))
    )
    with op.batch_alter_table('item_tag_recommendations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_item_tag_recommendations_item_id'), ['item_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_item_tag_recommendations_workflow_id'), ['workflow_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_item_tag_recommendations_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('item_tags',
    sa.Column('workspace_id', sa.GUID(length=16), nullable=False),
    sa.Column('item_id', sa.GUID(length=16), nullable=False),
    sa.Column('tag_id', sa.GUID(length=16), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id', 'item_id'], ['items.workspace_id', 'items.id'], name='fk_item_tags_item_workspace', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id', 'tag_id'], ['tags.workspace_id', 'tags.id'], name='fk_item_tags_tag_workspace', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('item_id', 'tag_id', name=op.f('pk_item_tags'))
    )
    with op.batch_alter_table('item_tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_item_tags_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('project_items',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('workspace_id', sa.GUID(length=16), nullable=False),
    sa.Column('project_id', sa.GUID(length=16), nullable=False),
    sa.Column('item_id', sa.GUID(length=16), nullable=False),
    sa.Column('added_by', sa.GUID(length=16), nullable=True),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['added_by'], ['users.id'], name=op.f('fk_project_items_added_by_users')),
    sa.ForeignKeyConstraint(['workspace_id', 'item_id'], ['items.workspace_id', 'items.id'], name='fk_project_items_item_workspace', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id', 'project_id'], ['projects.workspace_id', 'projects.id'], name='fk_project_items_project_workspace', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_items')),
    sa.UniqueConstraint('workspace_id', 'id', 'item_id', name='uq_project_items_workspace_id_item'),
    sa.UniqueConstraint('workspace_id', 'id', name='uq_project_items_workspace_id'),
    sa.UniqueConstraint('workspace_id', 'project_id', 'item_id', name='uq_project_items_workspace')
    )
    with op.batch_alter_table('project_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_items_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_items_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_items_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('project_participants',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('workspace_id', sa.GUID(length=16), nullable=False),
    sa.Column('project_id', sa.GUID(length=16), nullable=False),
    sa.Column('workspace_member_id', sa.GUID(length=16), nullable=False),
    sa.Column('user_id', sa.GUID(length=16), nullable=False),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id', 'project_id'], ['projects.workspace_id', 'projects.id'], name='fk_project_participants_project_workspace', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id', 'workspace_member_id', 'user_id'], ['workspace_members.workspace_id', 'workspace_members.id', 'workspace_members.user_id'], name='fk_project_participants_workspace_member', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_participants')),
    sa.UniqueConstraint('workspace_id', 'project_id', 'user_id', name='uq_project_participant_workspace')
    )
    with op.batch_alter_table('project_participants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_participants_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_participants_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_participants_workspace_id'), ['workspace_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_participants_workspace_member_id'), ['workspace_member_id'], unique=False)

    op.create_table('pdf_annotations',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('workspace_id', sa.GUID(length=16), nullable=False),
    sa.Column('file_revision_id', sa.GUID(length=16), nullable=False),
    sa.Column('item_id', sa.GUID(length=16), nullable=False),
    sa.Column('page_index', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.GUID(length=16), nullable=False),
    sa.Column('kind', sa.Enum('highlight', 'underline', 'strikeout', 'note', 'free_text', 'ink', 'rectangle', 'ellipse', 'line', 'arrow', name='annotation_kind', native_enum=False), nullable=False),
    sa.Column('scope', sa.Enum('private', 'project', name='annotation_scope', native_enum=False), nullable=False),
    sa.Column('project_item_id', sa.GUID(length=16), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('selected_text', sa.Text(), nullable=True),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'cockroachdb').with_variant(sa.ORA_JSONB(), 'oracle').with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTimeUTC(timezone=True), nullable=True),
    sa.Column('deleted_by_moderation', sa.Boolean(), server_default=sa.text('(false)'), nullable=False),
    sa.Column('hidden_at', sa.DateTimeUTC(timezone=True), nullable=True),
    sa.Column('archived_at', sa.DateTimeUTC(timezone=True), nullable=True),
    sa.Column('locked_at', sa.DateTimeUTC(timezone=True), nullable=True),
    sa.Column('moderated_by', sa.GUID(length=16), nullable=True),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.CheckConstraint("(scope = 'private' AND project_item_id IS NULL) OR (scope = 'project' AND project_item_id IS NOT NULL)", name=op.f('ck_pdf_annotations_project_scope')),
    sa.CheckConstraint("kind IN ('highlight', 'underline', 'strikeout', 'note', 'free_text', 'ink', 'rectangle', 'ellipse', 'line', 'arrow')", name=op.f('ck_pdf_annotations_kind')),
    sa.CheckConstraint("scope IN ('private', 'project')", name=op.f('ck_pdf_annotations_scope')),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_pdf_annotations_author_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id'], ['pdf_annotation_objects.id'], name='fk_pdf_annotations_object_id'),
    sa.ForeignKeyConstraint(['moderated_by'], ['users.id'], name=op.f('fk_pdf_annotations_moderated_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id', 'file_revision_id', 'item_id'], ['file_revisions.workspace_id', 'file_revisions.id', 'file_revisions.item_id'], name='fk_pdf_annotations_revision_item_workspace', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id', 'project_item_id', 'item_id'], ['project_items.workspace_id', 'project_items.id', 'project_items.item_id'], name='fk_pdf_annotations_project_item_revision_item', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pdf_annotations')),
    sa.UniqueConstraint('workspace_id', 'id', name='uq_pdf_annotations_workspace_id')
    )
    with op.batch_alter_table('pdf_annotations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pdf_annotations_author_id'), ['author_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pdf_annotations_file_revision_id'), ['file_revision_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pdf_annotations_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pdf_annotations_project_item_id'), ['project_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pdf_annotations_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('pdf_annotation_replies',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('workspace_id', sa.GUID(length=16), nullable=False),
    sa.Column('annotation_id', sa.GUID(length=16), nullable=False),
    sa.Column('author_id', sa.GUID(length=16), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTimeUTC(timezone=True), nullable=True),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_pdf_annotation_replies_author_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id'], ['pdf_annotation_objects.id'], name='fk_pdf_annotation_replies_object_id'),
    sa.ForeignKeyConstraint(['workspace_id', 'annotation_id'], ['pdf_annotations.workspace_id', 'pdf_annotations.id'], name='fk_pdf_annotation_replies_annotation_workspace', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pdf_annotation_replies'))
    )
    with op.batch_alter_table('pdf_annotation_replies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pdf_annotation_replies_annotation_id'), ['annotation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pdf_annotation_replies_author_id'), ['author_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pdf_annotation_replies_workspace_id'), ['workspace_id'], unique=False)

    # ### end Alembic commands ###

    if op.get_bind().dialect.name == "postgresql":
        op.execute(
            """
            CREATE TABLE item_search (
                item_id uuid PRIMARY KEY REFERENCES items(id) ON DELETE CASCADE,
                document tsvector NOT NULL
            )
            """
        )
        op.execute("CREATE INDEX ix_item_search_document ON item_search USING gin(document)")
        op.execute(
            """
            CREATE TABLE revision_search (
                revision_id uuid PRIMARY KEY REFERENCES file_revisions(id) ON DELETE CASCADE,
                item_id uuid NOT NULL,
                document tsvector NOT NULL
            )
            """
        )
        op.execute(
            "CREATE INDEX ix_revision_search_document ON revision_search USING gin(document)"
        )
        op.execute("CREATE INDEX ix_revision_search_item_id ON revision_search(item_id)")
    else:
        op.execute(
            """
            CREATE VIRTUAL TABLE item_search USING fts5(
                item_id UNINDEXED,
                content,
                tokenize='unicode61 remove_diacritics 2'
            )
            """
        )
        op.execute(
            """
            CREATE VIRTUAL TABLE revision_search USING fts5(
                revision_id UNINDEXED,
                item_id UNINDEXED,
                content,
                tokenize='unicode61 remove_diacritics 2'
            )
            """
        )

def schema_downgrades() -> None:
    """schema downgrade migrations go here."""
    op.execute("DROP TABLE IF EXISTS revision_search")
    op.execute("DROP TABLE IF EXISTS item_search")
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pdf_annotation_replies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pdf_annotation_replies_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_pdf_annotation_replies_author_id'))
        batch_op.drop_index(batch_op.f('ix_pdf_annotation_replies_annotation_id'))

    op.drop_table('pdf_annotation_replies')
    with op.batch_alter_table('pdf_annotations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pdf_annotations_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_pdf_annotations_project_item_id'))
        batch_op.drop_index(batch_op.f('ix_pdf_annotations_item_id'))
        batch_op.drop_index(batch_op.f('ix_pdf_annotations_file_revision_id'))
        batch_op.drop_index(batch_op.f('ix_pdf_annotations_author_id'))

    op.drop_table('pdf_annotations')
    with op.batch_alter_table('project_participants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_participants_workspace_member_id'))
        batch_op.drop_index(batch_op.f('ix_project_participants_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_project_participants_user_id'))
        batch_op.drop_index(batch_op.f('ix_project_participants_project_id'))

    op.drop_table('project_participants')
    with op.batch_alter_table('project_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_items_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_project_items_project_id'))
        batch_op.drop_index(batch_op.f('ix_project_items_item_id'))

    op.drop_table('project_items')
    with op.batch_alter_table('item_tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_item_tags_workspace_id'))

    op.drop_table('item_tags')
    with op.batch_alter_table('item_tag_recommendations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_item_tag_recommendations_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_item_tag_recommendations_workflow_id'))
        batch_op.drop_index(batch_op.f('ix_item_tag_recommendations_item_id'))

    op.drop_table('item_tag_recommendations')
    with op.batch_alter_table('item_reads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_item_reads_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_item_reads_last_read_at'))

    op.drop_table('item_reads')
    with op.batch_alter_table('item_identifiers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_item_identifiers_value'))
        batch_op.drop_index(batch_op.f('ix_item_identifiers_provider'))
        batch_op.drop_index(batch_op.f('ix_item_identifiers_item_id'))

    op.drop_table('item_identifiers')
    with op.batch_alter_table('item_authors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_item_authors_item_id'))
        batch_op.drop_index(batch_op.f('ix_item_authors_author_id'))

    op.drop_table('item_authors')
    with op.batch_alter_table('file_revisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_file_revisions_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_file_revisions_item_id'))

    op.drop_table('file_revisions')
    with op.batch_alter_table('discussion_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_discussion_messages_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_discussion_messages_project_id'))
        batch_op.drop_index(batch_op.f('ix_discussion_messages_item_id'))
        batch_op.drop_index(batch_op.f('ix_discussion_messages_author_id'))

    op.drop_table('discussion_messages')
    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attachments_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_attachments_item_id'))

    op.drop_table('attachments')
    with op.batch_alter_table('workspace_members', schema=None) as batch_op:
        batch_op.drop_index('uq_workspace_members_current_owner', sqlite_where=sa.text("terminated_at IS NULL AND role = 'owner'"), postgresql_where=sa.text("terminated_at IS NULL AND role = 'owner'"))
        batch_op.drop_index('uq_workspace_members_current', sqlite_where=sa.text('terminated_at IS NULL'), postgresql_where=sa.text('terminated_at IS NULL'))
        batch_op.drop_index(batch_op.f('ix_workspace_members_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_workspace_members_user_id'))

    op.drop_table('workspace_members')
    with op.batch_alter_table('workspace_invitations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workspace_invitations_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_workspace_invitations_user_id'))
        batch_op.drop_index(batch_op.f('ix_workspace_invitations_token_hash'))
        batch_op.drop_index(batch_op.f('ix_workspace_invitations_expires_at'))

    op.drop_table('workspace_invitations')
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tags_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_tags_normalized_name'))
        batch_op.drop_index(batch_op.f('ix_tags_name'))

    op.drop_table('tags')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_workspace_id'))

    op.drop_table('projects')
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_items_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_items_title'))
        batch_op.drop_index(batch_op.f('ix_items_doi'))
        batch_op.drop_index(batch_op.f('ix_items_bibtex_id'))

    op.drop_table('items')
    with op.batch_alter_table('import_batches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_import_batches_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_import_batches_workflow_id'))
        batch_op.drop_index(batch_op.f('ix_import_batches_actor_id'))

    op.drop_table('import_batches')
    with op.batch_alter_table('export_artifacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_export_artifacts_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_export_artifacts_expires_at'))

    op.drop_table('export_artifacts')
    with op.batch_alter_table('citation_styles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_citation_styles_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_citation_styles_created_by'))

    op.drop_table('citation_styles')
    op.drop_table('workspaces')
    op.drop_table('system_settings')
    with op.batch_alter_table('login_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_login_sessions_token_hash'))
        batch_op.drop_index(batch_op.f('ix_login_sessions_expires_at'))

    op.drop_table('login_sessions')
    with op.batch_alter_table('invitations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invitations_token_hash'))
        batch_op.drop_index(batch_op.f('ix_invitations_expires_at'))

    op.drop_table('invitations')
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_events_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_audit_events_project_id'))
        batch_op.drop_index(batch_op.f('ix_audit_events_action'))

    op.drop_table('audit_events')
    with op.batch_alter_table('api_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_api_tokens_token_hash'))
        batch_op.drop_index(batch_op.f('ix_api_tokens_expires_at'))

    op.drop_table('api_tokens')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))

    op.drop_table('users')
    op.drop_table('pdf_annotation_objects')
    with op.batch_alter_table('object_integrity_scans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_object_integrity_scans_checked_at'))

    op.drop_table('object_integrity_scans')
    op.drop_table('login_throttles')
    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_authors_last_name'))

    op.drop_table('authors')
    # ### end Alembic commands ###

def data_upgrades() -> None:
    """Add any optional data upgrade migrations here!"""

def data_downgrades() -> None:
    """Add any optional data downgrade migrations here!"""
