"""initial schema

Revision ID: a2254a6c211f
Revises:
Create Date: 2026-09-15 16:23:36.694528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2254a6c211f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authors',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('first_name', sa.String(length=120), nullable=True),
    sa.Column('last_name', sa.String(length=120), nullable=False),
    sa.Column('identity_key', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identity_key', name='uq_authors_identity')
    )
    op.create_index(op.f('ix_authors_last_name'), 'authors', ['last_name'], unique=False)
    op.create_table('export_artifacts',
    sa.Column('workflow_id', sa.String(length=255), nullable=False),
    sa.Column('object_key', sa.String(length=500), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('workflow_id'),
    sa.UniqueConstraint('object_key')
    )
    op.create_index(op.f('ix_export_artifacts_expires_at'), 'export_artifacts', ['expires_at'], unique=False)
    op.create_table('login_throttles',
    sa.Column('identity_hash', sa.String(length=64), nullable=False),
    sa.Column('failures', sa.Integer(), nullable=False),
    sa.Column('window_started_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('identity_hash')
    )
    op.create_table('object_integrity_scans',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('missing_count', sa.Integer(), nullable=False),
    sa.Column('mismatch_count', sa.Integer(), nullable=False),
    sa.Column('errors', sa.Text(), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_object_integrity_scans_checked_at'), 'object_integrity_scans', ['checked_at'], unique=False)
    op.create_table('pdf_annotation_objects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('object_type', sa.Enum('annotation', 'reply', name='annotation_object_type', native_enum=False), nullable=False),
    sa.CheckConstraint("object_type IN ('annotation', 'reply')", name='ck_pdf_annotation_objects_type'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('api_tokens',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_tokens_expires_at'), 'api_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_api_tokens_token_hash'), 'api_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_api_tokens_user_id'), 'api_tokens', ['user_id'], unique=False)
    op.create_table('audit_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=120), nullable=False),
    sa.Column('target_type', sa.String(length=80), nullable=False),
    sa.Column('target_id', sa.String(length=36), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_action'), 'audit_events', ['action'], unique=False)
    op.create_table('citation_styles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('csl_xml', sa.Text(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_citation_styles_created_by'), 'citation_styles', ['created_by'], unique=False)
    op.create_table('import_batches',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('file_format', sa.String(length=16), nullable=False),
    sa.Column('records', sa.Text(), nullable=False),
    sa.Column('errors', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('workflow_id', sa.String(length=255), nullable=True),
    sa.Column('committed_item_ids', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'ready', 'failed', 'committed')", name='ck_import_batches_status'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_batches_created_at'), 'import_batches', ['created_at'], unique=False)
    op.create_index(op.f('ix_import_batches_owner_id'), 'import_batches', ['owner_id'], unique=False)
    op.create_index(op.f('ix_import_batches_workflow_id'), 'import_batches', ['workflow_id'], unique=False)
    op.create_table('invitations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_invitations_expires_at'), 'invitations', ['expires_at'], unique=False)
    op.create_index(op.f('ix_invitations_token_hash'), 'invitations', ['token_hash'], unique=True)
    op.create_table('items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('publication_date', sa.String(length=32), nullable=True),
    sa.Column('publication_title', sa.Text(), nullable=True),
    sa.Column('volume', sa.String(length=100), nullable=True),
    sa.Column('issue', sa.String(length=100), nullable=True),
    sa.Column('pages', sa.String(length=100), nullable=True),
    sa.Column('affiliation', sa.Text(), nullable=True),
    sa.Column('publisher', sa.Text(), nullable=True),
    sa.Column('place_published', sa.String(length=255), nullable=True),
    sa.Column('journal_abbreviation', sa.Text(), nullable=True),
    sa.Column('doi', sa.String(length=500), nullable=True),
    sa.Column('identifiers', sa.Text(), nullable=True),
    sa.Column('reference_type', sa.String(length=40), nullable=True),
    sa.Column('authors', sa.Text(), nullable=True),
    sa.Column('editors', sa.Text(), nullable=True),
    sa.Column('bibtex_id', sa.String(length=255), nullable=True),
    sa.Column('bibtex_type', sa.String(length=40), nullable=True),
    sa.Column('urls', sa.Text(), nullable=True),
    sa.Column('keywords', sa.Text(), nullable=True),
    sa.Column('custom_fields', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_items_bibtex_id'), 'items', ['bibtex_id'], unique=False)
    op.create_index(op.f('ix_items_doi'), 'items', ['doi'], unique=False)
    op.create_index(op.f('ix_items_title'), 'items', ['title'], unique=False)
    op.create_table('login_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('csrf_token', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_login_sessions_expires_at'), 'login_sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_login_sessions_token_hash'), 'login_sessions', ['token_hash'], unique=True)
    op.create_table('projects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=240), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('state', sa.Enum('active', 'archived', name='project_state', native_enum=False), nullable=False),
    sa.Column('visibility', sa.Enum('private', 'public', name='project_visibility', native_enum=False), nullable=False),
    sa.CheckConstraint("state IN ('active', 'archived')", name='ck_projects_state'),
    sa.CheckConstraint("visibility IN ('private', 'public')", name='ck_projects_visibility'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_owner_id'), 'projects', ['owner_id'], unique=False)
    op.create_table('system_settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('tags',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tags_name'), 'tags', ['name'], unique=True)
    op.create_table('attachments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('item_id', sa.String(length=36), nullable=False),
    sa.Column('object_key', sa.String(length=200), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('graphical_abstract', name='attachment_role', native_enum=False), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("role IS NULL OR role = 'graphical_abstract'", name='ck_attachments_role'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_id', 'role', name='uq_attachments_item_role')
    )
    op.create_index(op.f('ix_attachments_item_id'), 'attachments', ['item_id'], unique=False)
    op.create_index(op.f('ix_attachments_object_key'), 'attachments', ['object_key'], unique=False)
    op.create_table('discussion_messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('item_id', sa.String(length=36), nullable=False),
    sa.Column('author_id', sa.String(length=36), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discussion_messages_author_id'), 'discussion_messages', ['author_id'], unique=False)
    op.create_index(op.f('ix_discussion_messages_item_id'), 'discussion_messages', ['item_id'], unique=False)
    op.create_table('file_revisions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('item_id', sa.String(length=36), nullable=False),
    sa.Column('object_key', sa.String(length=200), nullable=False),
    sa.Column('thumbnail_object_key', sa.String(length=200), nullable=True),
    sa.Column('thumbnail_size', sa.Integer(), nullable=True),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('page_geometry', sa.Text(), nullable=True),
    sa.Column('full_text', sa.Text(), nullable=True),
    sa.Column('processing_state', sa.Enum('pending', 'ready', name='file_revision_processing_state', native_enum=False), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("processing_state IN ('pending', 'ready')", name='ck_file_revisions_processing_state'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_file_revisions_item_id'), 'file_revisions', ['item_id'], unique=False)
    op.create_index(op.f('ix_file_revisions_object_key'), 'file_revisions', ['object_key'], unique=False)
    op.create_index(op.f('ix_file_revisions_thumbnail_object_key'), 'file_revisions', ['thumbnail_object_key'], unique=False)
    op.create_table('item_authors',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('item_id', sa.String(length=36), nullable=False),
    sa.Column('author_id', sa.String(length=36), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_corresponding', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['authors.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_id', 'author_id', 'role', name='uq_item_author_role')
    )
    op.create_index(op.f('ix_item_authors_author_id'), 'item_authors', ['author_id'], unique=False)
    op.create_index(op.f('ix_item_authors_item_id'), 'item_authors', ['item_id'], unique=False)
    op.create_table('item_identifiers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('item_id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('value', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_id', 'provider', 'value', name='uq_item_provider_value')
    )
    op.create_index(op.f('ix_item_identifiers_item_id'), 'item_identifiers', ['item_id'], unique=False)
    op.create_index(op.f('ix_item_identifiers_provider'), 'item_identifiers', ['provider'], unique=False)
    op.create_index(op.f('ix_item_identifiers_value'), 'item_identifiers', ['value'], unique=False)
    op.create_table('item_reads',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('item_id', sa.String(length=36), nullable=False),
    sa.Column('last_read_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'item_id')
    )
    op.create_index(op.f('ix_item_reads_last_read_at'), 'item_reads', ['last_read_at'], unique=False)
    op.create_table('item_tag_recommendations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('item_id', sa.String(length=36), nullable=False),
    sa.Column('generation_token', sa.Integer(), nullable=False),
    sa.Column('workflow_id', sa.String(length=255), nullable=True),
    sa.Column('single_words', sa.Text(), nullable=True),
    sa.Column('phrases', sa.Text(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('generation_token >= 1', name='ck_item_tag_recommendations_token'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_tag_recommendations_item_id'), 'item_tag_recommendations', ['item_id'], unique=True)
    op.create_index(op.f('ix_item_tag_recommendations_workflow_id'), 'item_tag_recommendations', ['workflow_id'], unique=False)
    op.create_table('item_tags',
    sa.Column('item_id', sa.String(length=36), nullable=False),
    sa.Column('tag_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('item_id', 'tag_id')
    )
    op.create_table('project_items',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('item_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'item_id')
    )
    op.create_table('project_members',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.Enum('owner', 'editor', 'viewer', name='project_role', native_enum=False), nullable=False),
    sa.CheckConstraint("role IN ('owner', 'editor', 'viewer')", name='ck_project_members_role'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'user_id')
    )
    op.create_table('pdf_annotations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('file_revision_id', sa.String(length=36), nullable=False),
    sa.Column('page_index', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.Enum('highlight', 'underline', 'strikeout', 'note', 'free_text', 'ink', 'rectangle', 'ellipse', 'line', 'arrow', name='annotation_kind', native_enum=False), nullable=False),
    sa.Column('scope', sa.Enum('private', 'project', name='annotation_scope', native_enum=False), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('selected_text', sa.Text(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("(scope = 'private' AND project_id IS NULL) OR (scope = 'project' AND project_id IS NOT NULL)", name='ck_pdf_annotations_project_scope'),
    sa.CheckConstraint("kind IN ('highlight', 'underline', 'strikeout', 'note', 'free_text', 'ink', 'rectangle', 'ellipse', 'line', 'arrow')", name='ck_pdf_annotations_kind'),
    sa.CheckConstraint("scope IN ('private', 'project')", name='ck_pdf_annotations_scope'),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['file_revision_id'], ['file_revisions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id'], ['pdf_annotation_objects.id'], name='fk_pdf_annotations_object_id'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pdf_annotations_author_id'), 'pdf_annotations', ['author_id'], unique=False)
    op.create_index(op.f('ix_pdf_annotations_file_revision_id'), 'pdf_annotations', ['file_revision_id'], unique=False)
    op.create_index(op.f('ix_pdf_annotations_project_id'), 'pdf_annotations', ['project_id'], unique=False)
    op.create_table('pdf_annotation_replies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('annotation_id', sa.String(length=36), nullable=False),
    sa.Column('author_id', sa.String(length=36), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['annotation_id'], ['pdf_annotations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id'], ['pdf_annotation_objects.id'], name='fk_pdf_annotation_replies_object_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pdf_annotation_replies_annotation_id'), 'pdf_annotation_replies', ['annotation_id'], unique=False)
    op.create_index(op.f('ix_pdf_annotation_replies_author_id'), 'pdf_annotation_replies', ['author_id'], unique=False)
    # ### end Alembic commands ###

    # The full-text search projections are dialect-specific and invisible to autogenerate.
    if op.get_bind().dialect.name == "postgresql":
        op.execute(
            """
            CREATE TABLE item_search (
                item_id varchar(36) PRIMARY KEY REFERENCES items(id) ON DELETE CASCADE,
                document tsvector NOT NULL
            )
            """
        )
        op.execute("CREATE INDEX ix_item_search_document ON item_search USING gin(document)")
        op.execute(
            """
            CREATE TABLE revision_search (
                revision_id varchar(36) PRIMARY KEY REFERENCES file_revisions(id) ON DELETE CASCADE,
                item_id varchar(36) NOT NULL,
                document tsvector NOT NULL
            )
            """
        )
        op.execute(
            "CREATE INDEX ix_revision_search_document ON revision_search USING gin(document)"
        )
        op.execute("CREATE INDEX ix_revision_search_item_id ON revision_search(item_id)")
    else:
        op.execute(
            """
            CREATE VIRTUAL TABLE item_search USING fts5(
                item_id UNINDEXED,
                content,
                tokenize='unicode61 remove_diacritics 2'
            )
            """
        )
        op.execute(
            """
            CREATE VIRTUAL TABLE revision_search USING fts5(
                revision_id UNINDEXED,
                item_id UNINDEXED,
                content,
                tokenize='unicode61 remove_diacritics 2'
            )
            """
        )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TABLE IF EXISTS revision_search")
    op.execute("DROP TABLE IF EXISTS item_search")
    op.drop_index(op.f('ix_pdf_annotation_replies_author_id'), table_name='pdf_annotation_replies')
    op.drop_index(op.f('ix_pdf_annotation_replies_annotation_id'), table_name='pdf_annotation_replies')
    op.drop_table('pdf_annotation_replies')
    op.drop_index(op.f('ix_pdf_annotations_project_id'), table_name='pdf_annotations')
    op.drop_index(op.f('ix_pdf_annotations_file_revision_id'), table_name='pdf_annotations')
    op.drop_index(op.f('ix_pdf_annotations_author_id'), table_name='pdf_annotations')
    op.drop_table('pdf_annotations')
    op.drop_table('project_members')
    op.drop_table('project_items')
    op.drop_table('item_tags')
    op.drop_index(op.f('ix_item_tag_recommendations_workflow_id'), table_name='item_tag_recommendations')
    op.drop_index(op.f('ix_item_tag_recommendations_item_id'), table_name='item_tag_recommendations')
    op.drop_table('item_tag_recommendations')
    op.drop_index(op.f('ix_item_reads_last_read_at'), table_name='item_reads')
    op.drop_table('item_reads')
    op.drop_index(op.f('ix_item_identifiers_value'), table_name='item_identifiers')
    op.drop_index(op.f('ix_item_identifiers_provider'), table_name='item_identifiers')
    op.drop_index(op.f('ix_item_identifiers_item_id'), table_name='item_identifiers')
    op.drop_table('item_identifiers')
    op.drop_index(op.f('ix_item_authors_item_id'), table_name='item_authors')
    op.drop_index(op.f('ix_item_authors_author_id'), table_name='item_authors')
    op.drop_table('item_authors')
    op.drop_index(op.f('ix_file_revisions_thumbnail_object_key'), table_name='file_revisions')
    op.drop_index(op.f('ix_file_revisions_object_key'), table_name='file_revisions')
    op.drop_index(op.f('ix_file_revisions_item_id'), table_name='file_revisions')
    op.drop_table('file_revisions')
    op.drop_index(op.f('ix_discussion_messages_item_id'), table_name='discussion_messages')
    op.drop_index(op.f('ix_discussion_messages_author_id'), table_name='discussion_messages')
    op.drop_table('discussion_messages')
    op.drop_index(op.f('ix_attachments_object_key'), table_name='attachments')
    op.drop_index(op.f('ix_attachments_item_id'), table_name='attachments')
    op.drop_table('attachments')
    op.drop_index(op.f('ix_tags_name'), table_name='tags')
    op.drop_table('tags')
    op.drop_table('system_settings')
    op.drop_index(op.f('ix_projects_owner_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_login_sessions_token_hash'), table_name='login_sessions')
    op.drop_index(op.f('ix_login_sessions_expires_at'), table_name='login_sessions')
    op.drop_table('login_sessions')
    op.drop_index(op.f('ix_items_title'), table_name='items')
    op.drop_index(op.f('ix_items_doi'), table_name='items')
    op.drop_index(op.f('ix_items_bibtex_id'), table_name='items')
    op.drop_table('items')
    op.drop_index(op.f('ix_invitations_token_hash'), table_name='invitations')
    op.drop_index(op.f('ix_invitations_expires_at'), table_name='invitations')
    op.drop_table('invitations')
    op.drop_index(op.f('ix_import_batches_workflow_id'), table_name='import_batches')
    op.drop_index(op.f('ix_import_batches_owner_id'), table_name='import_batches')
    op.drop_index(op.f('ix_import_batches_created_at'), table_name='import_batches')
    op.drop_table('import_batches')
    op.drop_index(op.f('ix_citation_styles_created_by'), table_name='citation_styles')
    op.drop_table('citation_styles')
    op.drop_index(op.f('ix_audit_events_action'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_api_tokens_user_id'), table_name='api_tokens')
    op.drop_index(op.f('ix_api_tokens_token_hash'), table_name='api_tokens')
    op.drop_index(op.f('ix_api_tokens_expires_at'), table_name='api_tokens')
    op.drop_table('api_tokens')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_table('pdf_annotation_objects')
    op.drop_index(op.f('ix_object_integrity_scans_checked_at'), table_name='object_integrity_scans')
    op.drop_table('object_integrity_scans')
    op.drop_table('login_throttles')
    op.drop_index(op.f('ix_export_artifacts_expires_at'), table_name='export_artifacts')
    op.drop_table('export_artifacts')
    op.drop_index(op.f('ix_authors_last_name'), table_name='authors')
    op.drop_table('authors')
    # ### end Alembic commands ###
