from __future__ import annotations

from quirebase.discovery.activity import get_user_imported_identifiers, record_search_audit
from quirebase.discovery.bibliography import (
    SUPPORTED_FORMATS,
    export_bibliography,
    parse_bibliography,
)
from quirebase.discovery.citations import (
    REFERENCE_TYPE_TO_CSL,
    CitationStyleOption,
    CitationStyleSelection,
    ExportOptions,
    builtin_style_xml,
    create_custom_citation_style,
    delete_custom_citation_style,
    format_csl_export,
    format_standard_export,
    get_item_citation_response,
    get_item_citation_text_response,
    is_valid_csl,
    item_to_csl_json,
    list_custom_citation_styles,
    render_bibliography,
    render_citation,
    resolve_style_xml,
    select_builtin_citation_styles,
)
from quirebase.discovery.imports import (
    BatchConflict,
    UpstreamServiceError,
    commit_import_batch,
    export_accessible_bibliography,
    export_selected_bibliography,
    import_published_pdf,
    import_unpublished_pdf,
    stage_import_batch,
    stage_metadata_batch,
)
from quirebase.discovery.lookup import (
    Identifier,
    MetadataLookupError,
    MetadataNotFoundError,
    MetadataRecord,
    lookup_metadata,
    parse_identifier,
)
from quirebase.discovery.search import (
    SearchClause,
    SearchPage,
    SearchResult,
    search_metadata,
)

__all__ = [
    "REFERENCE_TYPE_TO_CSL",
    "SUPPORTED_FORMATS",
    "BatchConflict",
    "CitationStyleOption",
    "CitationStyleSelection",
    "ExportOptions",
    "Identifier",
    "MetadataLookupError",
    "MetadataNotFoundError",
    "MetadataRecord",
    "SearchClause",
    "SearchPage",
    "SearchResult",
    "UpstreamServiceError",
    "builtin_style_xml",
    "commit_import_batch",
    "create_custom_citation_style",
    "delete_custom_citation_style",
    "export_accessible_bibliography",
    "export_bibliography",
    "export_selected_bibliography",
    "format_csl_export",
    "format_standard_export",
    "get_item_citation_response",
    "get_item_citation_text_response",
    "get_user_imported_identifiers",
    "import_published_pdf",
    "import_unpublished_pdf",
    "is_valid_csl",
    "item_to_csl_json",
    "list_custom_citation_styles",
    "lookup_metadata",
    "parse_bibliography",
    "parse_identifier",
    "record_search_audit",
    "render_bibliography",
    "render_citation",
    "resolve_style_xml",
    "search_metadata",
    "select_builtin_citation_styles",
    "stage_import_batch",
    "stage_metadata_batch",
]
